on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  draft_release:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # - name: Set environment variables for Windows
      #   if: matrix.os == 'windows-latest'
      #   env:
      #     DATABASE_URL: file://C:/Windows_Database.db
      #   run: echo "$env.DATABASE_URL"

      # - name: Set environment variables for macOS and Linux
      #   if: matrix.os == 'macos-latest' || matrix.os == 'linux-latest'
      #   env:
      #     DATABASE_URL: file:///database.db
      #   run: echo "$DATABASE_URL"

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run build
        env:
          DATABASE_URL: ${{ matrix.os == 'windows-latest' && 'file://C:/tmp/Windows_Database.db' || 'file:///Users/runner/work/sing/db/db.db'}}

      - run: npx --no-install electron-builder --publish always
        env:
          DATABASE_URL: "file://C:/Windows_Database.db"
          GH_TOKEN: ${{ secrets.TEST_SECRET }}
