on: workflow_dispatch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  WINDOWS_DATABASE_PATH: 'file:${{github.workspace}}\windows_database.db'
  UNIX_DATABASE_PATH: 'file:${{github.workspace}}/unix_database.db'


jobs:
  draft_release:
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}


    steps:
      - if: runner.os == 'Windows'
        run: echo "The db path should be $env:WINDOWS_DATABASE_PATH."

      - if: runner.os != 'Windows'
        run: echo "The db path should be $UNIX_DATABASE_PATH."

      - uses: actions/checkout@v3
        with: 
          lfs: true

      - run: git lfs checkout

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run build
        env:
          DATABASE_URL: ${{ runner.os == 'Windows' && env.WINDOWS_DATABASE_PATH || env.UNIX_DATABASE_PATH }}

      - run: npx --no-install electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.github_token }}
